<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="DESKTOP-ONBI019" name="SeleniumFrameworkDesign.Test.ErrorValidationTest" tests="3" failures="1" timestamp="12 Jan 2023 16:18:33 GMT" time="30.419" errors="0">
  <testcase name="loginErrorValidationTest" time="8.271" classname="SeleniumFrameworkDesign.Test.ErrorValidationTest">
    <skipped/>
  </testcase> <!-- loginErrorValidationTest -->
  <testcase name="loginErrorValidationTest" time="12.251" classname="SeleniumFrameworkDesign.Test.ErrorValidationTest">
    <skipped/>
  </testcase> <!-- loginErrorValidationTest -->
  <testcase name="loginErrorValidationTest" time="9.897" classname="SeleniumFrameworkDesign.Test.ErrorValidationTest">
    <failure type="java.lang.AssertionError" message="expected [Incorrect email or password.] but found [Incorrect email and password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email and password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at SeleniumFrameworkDesign.Test.ErrorValidationTest.loginErrorValidationTest(ErrorValidationTest.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- loginErrorValidationTest -->
</testsuite> <!-- SeleniumFrameworkDesign.Test.ErrorValidationTest -->
